// Generated by Skyramp v1.3.11 on 2026-03-11 12:14:33.077927981 +0000 UTC m=+212.273828068
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Application-Id \
// 		--chaining-key response.id \
// 		--framework playwright \
// 		--language typescript \
// 		--output email_verification_flow.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec/scenario_email_verification_flow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = "http://localhost:1337";

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const usersPostRequestBody = `{
            "email": "verifytest_1741690331@example.com",
            "password": "TestPass1",
            "username": "verifytest_1741690331"
        }`
    
    // Execute Request
    let usersPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/users",
        method:"POST",
        body:usersPostRequestBody,
        headers:{"X-Parse-Application-Id": ""}
    });

    // Generated Assertions
    expect(usersPostResponse.statusCode, 'status code').toBe(201);

    // Request Body
    const resendVerificationEmailPostRequestBody = `{
            "email": "verifytest_1741690331@example.com"
        }`
    
    // Execute Request
    let resendVerificationEmailPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/resendVerificationEmail",
        method:"POST",
        body:resendVerificationEmailPostRequestBody,
        headers:{"X-Parse-Application-Id": ""}
    });

    // Generated Assertions
    expect(resendVerificationEmailPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const verifyEmailPostRequestBody = `{
            "token": "verifytoken123abc"
        }`
    
    // Execute Request
    let verifyEmailPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/verifyEmail",
        method:"POST",
        body:verifyEmailPostRequestBody,
        headers:{"X-Parse-Application-Id": ""},
        dataOverride:{"token": getResponseValue(resendVerificationEmailPostResponse, "result.token")}
    });

    // Generated Assertions
    expect(verifyEmailPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const loginPostRequestBody = `{
            "password": "TestPass1",
            "username": "verifytest_1741690331"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:{"X-Parse-Application-Id": ""},
        dataOverride:{"username": getResponseValue(verifyEmailPostResponse, "result.username")}
    });

    // Generated Assertions
    expect(loginPostResponse.statusCode, 'status code').toBe(200);
});

