// Generated by Skyramp v1.3.11 on 2026-03-11 12:41:45.488208584 +0000 UTC m=+158.631216683
// Command: skyramp generate contract rest http://localhost:1337/parse/functions/resendVerificationEmail \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output resend_verification_email_contract.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec \
// 		--overwrite \
// 		--request-data {"email":"testuser@example.com"} \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:1337";

// contract test for /parse/functions/resendVerificationEmail POST
test('testResendVerificationEmailPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const resendVerificationEmailPostRequestBody: string = `{
        "email": "testuser@example.com"
    }`;

    // Execute Request
    const resendVerificationEmailPostResponse = await client.sendRequest({
        url: URL,
        path: "/parse/functions/resendVerificationEmail",
        method: "POST",
        body: resendVerificationEmailPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(resendVerificationEmailPostResponse, "20x"), 'status code').toBeTruthy();
});
