// Generated by Skyramp v1.3.11 on 2026-03-11 12:14:18.418810043 +0000 UTC m=+197.614710130
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Application-Id \
// 		--chaining-key response.id \
// 		--framework playwright \
// 		--language typescript \
// 		--output unverified_login_blocked.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec/scenario_unverified_login_blocked.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = "http://localhost:1337";

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const usersPostRequestBody = `{
            "email": "unveriftest_1741690331@example.com",
            "password": "TestPass1",
            "username": "unveriftest_1741690331"
        }`
    
    // Execute Request
    let usersPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/users",
        method:"POST",
        body:usersPostRequestBody,
        headers:{"X-Parse-Application-Id": ""}
    });

    // Generated Assertions
    expect(usersPostResponse.statusCode, 'status code').toBe(201);

    // Request Body
    const loginPostRequestBody = `{
            "password": "TestPass1",
            "username": "unveriftest_1741690331"
        }`
    
    // Execute Request
    let loginPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/login",
        method:"POST",
        body:loginPostRequestBody,
        headers:{"X-Parse-Application-Id": ""}
    });

    // Generated Assertions
    expect(loginPostResponse.statusCode, 'status code').toBe(400);
});

