// Generated by Skyramp v1.3.11 on 2026-03-11 12:41:45.781356591 +0000 UTC m=+158.924364690
// Command: skyramp generate contract rest http://localhost:1337/parse/users \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output user_registration_contract.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec \
// 		--overwrite \
// 		--request-data {"username":"contracttest_1741690400","password":"TestPass1","email":"contracttest_1741690400@example.com"} \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:1337";

// contract test for /parse/users POST
test('testUsersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const usersPostRequestBody: string = `{
        "email": "contracttest_1741690400@example.com",
        "password": "TestPass1",
        "username": "contracttest_1741690400"
    }`;

    // Execute Request
    const usersPostResponse = await client.sendRequest({
        url: URL,
        path: "/parse/users",
        method: "POST",
        body: usersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(usersPostResponse, "20x"), 'status code').toBeTruthy();
});
