// Generated by Skyramp v1.3.11 on 2026-03-11 12:14:18.561115548 +0000 UTC m=+197.757015665
// Command: skyramp generate fuzz rest http://localhost:1337/parse/users \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output user_signup_validation_fuzz.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec \
// 		--overwrite \
// 		--request-data {"username":"testuser","password":"TestPass1","email":"testuser@example.com"} \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:1337";

// fuzz test for /parse/users POST
test('testUsersPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const usersPostRequestBody = `{
            "username": "testuser",
            "password": "TestPass1",
            "email": "testuser@example.com"
        }`
    
    // Fuzz strategies
    const usersPostFuzzedBody = {
        "email": "0123456789",
        "password": "0123456789",
        "username": "0123456789"
    };
    // Fuzz status codes
    const expectedUsersPostStatusCode: Record<string, string> = {
        "email": "40x",
        "password": "40x",
        "username": "40x"
    };
    // Fuzz status codes for Null values
    const expectedUsersPostNullStatusCode: Record<string, string> = {
        "email": "40x",
        "password": "40x",
        "username": "40x"
    };

    // Execute Request
    let usersPostResponse = await client.sendRequest({
        url:URL,
        path:"/parse/users",
        method:"POST",
        body:usersPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(usersPostFuzzedBody)) {
        // Execute Request
        usersPostResponse = await client.sendRequest({
            url:URL,
            path:"/parse/users",
            method:"POST",
            body:usersPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(usersPostFuzzedBody, key)},
            expectedCode:getValue(expectedUsersPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(usersPostFuzzedBody, key)}`
        });


        // Execute Request
        usersPostResponse = await client.sendRequest({
            url:URL,
            path:"/parse/users",
            method:"POST",
            body:usersPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedUsersPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

