// Generated by Skyramp v1.3.11 on 2026-03-11 12:41:45.405976838 +0000 UTC m=+158.548984947
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Application-Id \
// 		--chaining-key response.id \
// 		--framework playwright \
// 		--language typescript \
// 		--output username_duplicate_rejection.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec/scenario_username_duplicate_rejection.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = "http://localhost:1337";

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const usersPostRequestBody = `{
            "email": "duptest_1741690400@example.com",
            "password": "TestPass1",
            "username": "duptest_1741690400"
        }`
    
    // Execute Request
    let usersPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/users",
        method:"POST",
        body:usersPostRequestBody,
        headers:{"X-Parse-Application-Id": ""}
    });

    // Generated Assertions
    expect(usersPostResponse.statusCode, 'status code').toBe(201);

    // Request Body
    const usersPost1RequestBody = `{
            "email": "duptest2_1741690400@example.com",
            "password": "TestPass1",
            "username": "duptest_1741690400"
        }`
    
    // Execute Request
    let usersPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/users",
        method:"POST",
        body:usersPost1RequestBody,
        headers:{"X-Parse-Application-Id": ""}
    });

    // Generated Assertions
    expect(usersPost1Response.statusCode, 'status code').toBe(400);
});

