// Generated by Skyramp v1.3.11 on 2026-03-11 12:14:18.697672925 +0000 UTC m=+197.893573022
// Command: skyramp generate contract rest http://localhost:1337/parse/functions/verifyEmail \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output verify_email_contract.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec \
// 		--overwrite \
// 		--request-data {"token":"validtoken123"} \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:1337";

// contract test for /parse/functions/verifyEmail POST
test('testVerifyEmailPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const verifyEmailPostRequestBody: string = `{
        "token": "validtoken123"
    }`;

    // Execute Request
    const verifyEmailPostResponse = await client.sendRequest({
        url: URL,
        path: "/parse/functions/verifyEmail",
        method: "POST",
        body: verifyEmailPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(verifyEmailPostResponse, "20x"), 'status code').toBeTruthy();
});
