// Generated by Skyramp v1.3.11 on 2026-03-11 12:41:45.637814454 +0000 UTC m=+158.780822553
// Command: skyramp generate fuzz rest http://localhost:1337/parse/functions/verifyEmail \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output verify_email_fuzz.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example-testb/parse-server-example-testb/spec \
// 		--overwrite \
// 		--request-data {"token":"validtoken123"} \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = "http://localhost:1337";

// fuzz test for /parse/functions/verifyEmail POST
test('testVerifyEmailPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const verifyEmailPostRequestBody = `{
            "token": "validtoken123"
        }`
    
    // Fuzz strategies
    const verifyEmailPostFuzzedBody = {"token": "0123456789"};
    // Fuzz status codes
    const expectedVerifyEmailPostStatusCode: Record<string, string> = {"token": "40x"};
    // Fuzz status codes for Null values
    const expectedVerifyEmailPostNullStatusCode: Record<string, string> = {"token": "40x"};

    // Execute Request
    let verifyEmailPostResponse = await client.sendRequest({
        url:URL,
        path:"/parse/functions/verifyEmail",
        method:"POST",
        body:verifyEmailPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(verifyEmailPostFuzzedBody)) {
        // Execute Request
        verifyEmailPostResponse = await client.sendRequest({
            url:URL,
            path:"/parse/functions/verifyEmail",
            method:"POST",
            body:verifyEmailPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(verifyEmailPostFuzzedBody, key)},
            expectedCode:getValue(expectedVerifyEmailPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(verifyEmailPostFuzzedBody, key)}`
        });


        // Execute Request
        verifyEmailPostResponse = await client.sendRequest({
            url:URL,
            path:"/parse/functions/verifyEmail",
            method:"POST",
            body:verifyEmailPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedVerifyEmailPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

